# i3 color palette — dark (purple/black)

# class                 border  backgr. text    indicator child_border
client.focused          #a000ff #a000ff #ffffff #a000ff   #a000ff
client.focused_inactive #480073 #480073 #ffffff #480073   #480073
client.unfocused        #595959 #595959 #888888 #595959   #595959
client.urgent           #ff0000 #ff0000 #ffffff #ff0000   #ff0000

bar {
	status_command ~/.scripts/i3status-wrapper
	position top
	tray_output primary

	colors {
		background #000000
		statusline #ffffff
		separator  #666666

		focused_workspace  #a000ff #a000ff #ffffff
		active_workspace   #480073 #480073 #ffffff
		inactive_workspace #333333 #222222 #888888
		urgent_workspace   #ff0000 #ff0000 #ffffff
	}
}
