# i3 color palette — light (gruvbox-inspired)

# class                 border  backgr. text    indicator child_border
client.focused          #b57614 #b57614 #fbf1c7 #b57614   #b57614
client.focused_inactive #d5c4a1 #d5c4a1 #3c3836 #d5c4a1   #d5c4a1
client.unfocused        #ebdbb2 #ebdbb2 #665c54 #ebdbb2   #ebdbb2
client.urgent           #cc241d #cc241d #fbf1c7 #cc241d   #cc241d

bar {
	status_command ~/.scripts/i3status-wrapper
	position top
	tray_output primary

	colors {
		background #f2e5bc
		statusline #3c3836
		separator  #928374

		focused_workspace  #b57614 #b57614 #fbf1c7
		active_workspace   #d79921 #d79921 #3c3836
		inactive_workspace #ebdbb2 #f9f5d7 #665c54
		urgent_workspace   #cc241d #cc241d #fbf1c7
	}
}
