version = "1.1.16"

[class]
DEFAULT = "n/a"  # example default icon (a question mark or generic app icon)
Brave = "󰇧"
firefox = ""
code = "󰨞"
# Alacritty = "\uea85"
telegram = "\ue217"
discord = "\uf1ff" 
Alacritty = ""
nautilus = ""
steam = "\uf1b6"
caja = ""

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]

[title_in_class]

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]

[format]
dedup = true
dedup_inactive_fullscreen = true
delim = " "
workspace = "{id}:{delim}{clients}"
workspace_empty = "{id}"
client = "{icon}"
client_fullscreen = "{icon}"
client_active = "{icon}"
client_dup = "{icon}{counter_sup}"
client_dup_active = "{icon}{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
