local wezterm = require 'wezterm'
local config = wezterm.config_builder()

local is_macos = wezterm.target_triple:find 'darwin' ~= nil

config.font = wezterm.font_with_fallback {
  'Source Code Pro', -- real italics, unlike Noto Sans Mono
  'Noto Sans Mono',
  'Hack Nerd Font Mono',
  'Noto Sans Mono CJK SC',
}
config.font_size = 10.7 -- matches the previous manual CTRL-minus CTRL-minus from 13.0
config.line_height = 1.0
config.cell_width = 0.9

config.color_scheme_dirs = { os.getenv 'HOME' .. '/.config/wezterm/colors' }

config.use_fancy_tab_bar = false
config.tab_bar_at_bottom = false
config.hide_tab_bar_if_only_one_tab = true


config.window_decorations = 'TITLE | RESIZE'
if is_macos then
  config.window_decorations = 'RESIZE'

  -- config.window_frame = {
  --   border_left_width    = '0.8cell',
  --   border_right_width   = '0.8cell',
  --   border_top_height    = '0.5cell',
  --   border_bottom_height = '0.5cell',
  --   border_left_color    = '#b8bb26',
  --   border_right_color   = '#b8bb26',
  --   border_top_color     = '#b8bb26',
  --   border_bottom_color  = '#b8bb26',
  -- }
end

config.window_background_opacity = 0.50 -- light mode bumps this in apply_theme
-- macOS has no compositor glass (hyprglass); use wezterm's built-in blur
-- behind a less transparent window or text gets murky.
config.macos_window_background_blur = 0
if is_macos then
  config.window_background_opacity = 0.85
  config.macos_window_background_blur = 50
end

config.default_cursor_style = 'BlinkingBlock'
config.cursor_blink_rate = 500

config.keys = {
  {
    key = 'Return',
    mods = 'SHIFT',
    action = wezterm.action.SendString '\x1b\r',
  },
  { key = '1', mods = 'CTRL', action = wezterm.action.SendString '\x1b[49;5u' },
  { key = '2', mods = 'CTRL', action = wezterm.action.SendString '\x1b[50;5u' },
  { key = '3', mods = 'CTRL', action = wezterm.action.SendString '\x1b[51;5u' },
  { key = '4', mods = 'CTRL', action = wezterm.action.SendString '\x1b[52;5u' },
  { key = '5', mods = 'CTRL', action = wezterm.action.SendString '\x1b[53;5u' },
  { key = '6', mods = 'CTRL', action = wezterm.action.SendString '\x1b[54;5u' },
  { key = '7', mods = 'CTRL', action = wezterm.action.SendString '\x1b[55;5u' },
  { key = '8', mods = 'CTRL', action = wezterm.action.SendString '\x1b[56;5u' },
  { key = '9', mods = 'CTRL', action = wezterm.action.SendString '\x1b[57;5u' },
}

-- Ultra power-save (~/.scripts/powersave) writes 1/0 here. Watching it means a
-- toggle reloads the config, which re-runs apply_theme below.
local ultra_state = (os.getenv 'XDG_RUNTIME_DIR' or '/tmp') .. '/ultrasave'
wezterm.add_to_config_reload_watch_list(ultra_state)
local function ultra_save()
  local f = io.open(ultra_state)
  if not f then return false end
  local v = f:read '*l'
  f:close()
  return v == '1'
end

-- colors.lua is generated by ~/.scripts/theme-apply (Linux); touch on this file reloads
local function apply_theme()
  -- no theme-apply on macOS: follow the OS dark/light mode instead.
  -- wezterm reloads this config on appearance change by itself.
  if is_macos then
    -- wezterm re-runs this config on OS appearance change only when
    -- get_appearance() is called here.
    local dark = wezterm.gui.get_appearance():find 'Dark' ~= nil
    -- light bg needs more body over the blurred wallpaper (see below)
      config.color_scheme = dark and 'GruvboxDarkHard' or 'Gruvbox light, medium (base16)'
      config.window_background_opacity = dark and 0.75 or 0.55
      -- sync nvim + gtmux with the OS mode (no-op if unchanged)
      io.popen(os.getenv 'HOME' .. '/.scripts/theme-sync-mac ' .. (dark and 'dark' or 'light') .. ' &')
      return dark and 'dark' or 'light'
  end

  -- LINUX config

  local ok, t = pcall(dofile, os.getenv 'HOME' .. '/.config/wezterm/colors.lua')
  if not ok then
    return 'dark'
  end

  config.colors = t.colors

  -- a light bg at 0.50 lands mid-grey over most wallpapers; give it more body
  config.window_background_opacity = t.mode == 'light' and 0.70 or 0.50

  -- opaque in ultra power-save: nothing behind the window gets composited, and
  -- with hyprglass off translucency would just be unblurred see-through
  if ultra_save() then config.window_background_opacity = 1.0 end

  config.window_frame = {
    active_titlebar_bg = t.titlebar,
    inactive_titlebar_bg = t.titlebar
  }
  return t.mode
end

apply_theme()

wezterm.on('window-config-reloaded', function(window)
  apply_theme()
end)

wezterm.on('update-right-status', function(window, pane)
  if apply_theme() == 'light' then
    window:set_right_status(wezterm.format { { Text = '  ☀  ' } })
  end
end)

return config
