local wezterm = require 'wezterm'
local config = wezterm.config_builder()

config.font = wezterm.font_with_fallback {
  'Source Code Pro', -- real italics, unlike Noto Sans Mono
  'Noto Sans Mono',
  'Hack Nerd Font Mono',
  'Noto Sans Mono CJK SC',
}
config.font_size = 10.7 -- matches the previous manual CTRL-minus CTRL-minus from 13.0
config.line_height = 1.0
config.cell_width = 0.9

config.color_scheme_dirs = { os.getenv 'HOME' .. '/.config/wezterm/colors' }

config.use_fancy_tab_bar = false
config.tab_bar_at_bottom = false
config.hide_tab_bar_if_only_one_tab = true

config.window_decorations = 'TITLE | RESIZE'
config.window_background_opacity = 0.50 -- light mode bumps this in apply_theme
config.macos_window_background_blur = 0

config.default_cursor_style = 'BlinkingBlock'
config.cursor_blink_rate = 500

config.keys = {
  {
    key = 'Return',
    mods = 'SHIFT',
    action = wezterm.action.SendString '\x1b\r',
  },
  { key = '1', mods = 'CTRL', action = wezterm.action.SendString '\x1b[49;5u' },
  { key = '2', mods = 'CTRL', action = wezterm.action.SendString '\x1b[50;5u' },
  { key = '3', mods = 'CTRL', action = wezterm.action.SendString '\x1b[51;5u' },
  { key = '4', mods = 'CTRL', action = wezterm.action.SendString '\x1b[52;5u' },
  { key = '5', mods = 'CTRL', action = wezterm.action.SendString '\x1b[53;5u' },
  { key = '6', mods = 'CTRL', action = wezterm.action.SendString '\x1b[54;5u' },
  { key = '7', mods = 'CTRL', action = wezterm.action.SendString '\x1b[55;5u' },
  { key = '8', mods = 'CTRL', action = wezterm.action.SendString '\x1b[56;5u' },
  { key = '9', mods = 'CTRL', action = wezterm.action.SendString '\x1b[57;5u' },
}

-- colors.lua is generated by ~/.scripts/theme-apply; touch on this file reloads
local function apply_theme()
  local ok, t = pcall(dofile, os.getenv 'HOME' .. '/.config/wezterm/colors.lua')
  if not ok then return 'dark' end
  config.colors = t.colors
  -- a light bg at 0.50 lands mid-grey over most wallpapers; give it more body
  config.window_background_opacity = t.mode == 'light' and 0.70 or 0.50
  config.window_frame = { active_titlebar_bg = t.titlebar, inactive_titlebar_bg = t.titlebar }
  return t.mode
end

apply_theme()

wezterm.on('window-config-reloaded', function(window)
  apply_theme()
end)

wezterm.on('update-right-status', function(window, pane)
  if apply_theme() == 'light' then
    window:set_right_status(wezterm.format { { Text = '  ☀  ' } })
  end
end)

return config
