local M = {}

-- ~/.config/nvim/colors.lua is generated by ~/.scripts/theme-apply from the
-- active themes/<name>.json. Absent (e.g. macOS, where theme-apply never runs)
-- we fall back to the builtin dark/light pair below.
local function generated()
  local ok, t = pcall(dofile, vim.fn.expand("~/.config/nvim/colors.lua"))
  if ok and type(t) == "table" and t.palette then return t end
end

local function apply(mode)
  local gen = generated()
  if gen then
    vim.api.nvim_set_option_value("background", gen.mode or mode, {})
    require("mini.base16").setup({ palette = gen.palette })
    -- mini.base16 sets highlights directly without firing ColorScheme; the
    -- transparency/spell fixups in custom/plugins/colors.lua hang off it.
    vim.api.nvim_exec_autocmds("ColorScheme", {})
    return
  end
  if mode == "dark" then
    vim.api.nvim_set_option_value("background", "dark", {})
    vim.cmd("colorscheme tokyonight")
  elseif mode == "light" then
    vim.api.nvim_set_option_value("background", "light", {})
    vim.cmd("colorscheme gruvbox")
  else
    vim.notify("Unknown theme mode: " .. tostring(mode), vim.log.levels.WARN)
  end
end

function M.apply(mode)
  apply(mode)
end

vim.api.nvim_create_user_command("ThemeSync", function(opts)
  local mode = opts.args

  if mode == "" then
    local mode_file = vim.fn.expand("~/.theme-mode")
    if vim.fn.filereadable(mode_file) == 1 then
      mode = vim.trim(table.concat(vim.fn.readfile(mode_file), "\n"))
    end
  end

  if mode == "" then
    mode = "dark" -- default when no file exists
  end

  apply(mode)
end, {
  nargs = "?",
  complete = function()
    return { "dark", "light" }
  end,
})

return M
