-- ============================================================================
-- Hyprland entry point (Lua).
-- Since Hyprland 0.55, if this file exists it is loaded INSTEAD of hyprland.conf.
-- The check is startup-only, so hyprland.conf stays as an instant fallback:
-- delete/rename this file and restart Hyprland to go back.
--
-- Load order: base -> colors (theme) -> binds -> plugins -> host overlay.
-- require() in Hyprland is a custom per-call scope and re-runs on reload,
-- so theme switching (theme-apply rewrites colors.lua + hyprctl reload) works.
-- ============================================================================

local function hostname()
    local h = os.getenv("HOSTNAME")
    if h and #h > 0 then return h end
    local f = io.open("/etc/hostname")
    if f then
        local s = f:read("l")
        f:close()
        if s and #s > 0 then return s end
    end
    return "unknown"
end

-- extra tiled layouts (from Hyprland's example/layouts), selectable as lua:<name>
-- registered before base so .layout entries referencing them resolve
require("layouts/spiral")
require("layouts/grid")
require("layouts/columns")
require("layouts/accordion")
require("base")
-- colors.lua is generated by ~/.scripts/theme-apply and gitignored; on a
-- fresh host it may not exist yet — start unthemed rather than not at all
pcall(require, "colors")
require("binds")
require("plugins")
require("hosts/" .. hostname())
