#!/bin/sh

if [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
    # Start GNOME Keyring Daemon and export variables
    eval "$(gnome-keyring-daemon --start --components=secrets,pkcs11,ssh,gpg)"
    export SSH_AUTH_SOCK

    # Optionally, start other services here

    exec Hyprland >/dev/null
fi
