#!/usr/bin/env bash

set -u

CONFIG="$HOME/.config/waybar/config.jsonc"
STYLE="$HOME/.config/waybar/style.css"
STATE_DIR="$HOME/.local/state/waybar"
LOG_FILE="$STATE_DIR/waybar.log"

mkdir -p "$STATE_DIR"
: >"$LOG_FILE"

exec waybar -c "$CONFIG" -s "$STYLE" >>"$LOG_FILE" 2>&1
